version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Exclusive: Tell it to run your specific GitHub Action for verification
    open-pull-requests-limit: 10