apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-manager-deploy  # Name of the deployment
spec:
  replicas: 2 # specifies how many identical replicas (pods) of the application should be maintained, in this case, 2, which means Kubernetes will ensure that two pods running the specified container are always available
  selector:
    matchLabels:
      app: todo-manager  # Selector to match pods managed by this deployment
  template:
    metadata:
      labels:
        app: todo-manager
      annotations:
        restartedAt: '56'
    spec:
      containers:
        - name: todo-manager  # Name of the container
          image: todomanagerregistry.azurecr.io/todo-manager:56
          imagePullPolicy: IfNotPresent   # Do not pull from Docker Hub
          ports:
            - containerPort: 5050  # Port that the container exposes
          
---
apiVersion: v1
kind: Service
metadata:
  name: todo-manager-service  # The name of the "Door"
spec:
  type: LoadBalancer          # 👈 Asking Azure for a Public IP
  selector:
    app: todo-manager         # Must match the label in your Deployment
  ports:
    - protocol: TCP
      port: 80                # The world connects to Port 80 (HTTP)
      targetPort: 5050        # We forward it to your Container's Port 5050
